version: "2"
services:
    wordpress:
        image: wordpress:latest
        ports:
            - "8000:80"
        depends_on:
            - mysql
        environment:
            VIRTUAL_HOST: example.net,example.net
            LETSENCRYPT_HOST: example.net,www.example.net
            LETSENCRYPT_EMAIL: webmaster@example.net
            WORDPRESS_DB_HOST: "mysql:3306"
        env_file: .env
    mysql:
      image: mysql:5.7
      env_file: .env
      command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --skip-character-set-client-handshake
      restart: always

networks:
  default:
    external:
      name: shared

